"""Add user_id to grocery_items

Revision ID: e3ab95fabac1
Revises: 6392a9ac571d
Create Date: 2025-05-15 22:44:18.721450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ab95fabac1'
down_revision = '6392a9ac571d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # Update existing rows to set a default user_id
    op.execute('UPDATE grocery_items SET user_id = 1 WHERE user_id IS NULL')

    # Alter the column to be non-nullable
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_items', schema=None) as batch_op:
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###